// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DivingClubs.Dao.SqlServer.Datas;

public partial class AddressEntity
{
    public int Id { get; set; }

    public string StreetNumber { get; set; }

    public string Street { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public virtual ICollection<DivingClubEntity> DivingClubEntities { get; set; } = new List<DivingClubEntity>();

    public virtual ICollection<PersonEntity> PersonEntities { get; set; } = new List<PersonEntity>();
}