// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DivingClubs.Dao.SqlServer.Datas;

public partial class DivingGroupEntity
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public int MinimumRank { get; set; }

    public int? MonitorId { get; set; }

    public int? ClubId { get; set; }

    public virtual DivingClubEntity Club { get; set; }

    public virtual MonitorEntity Monitor { get; set; }

    public virtual ICollection<LicenceEntity> LicenceEntities { get; set; } = new List<LicenceEntity>();
}