// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DivingClubs.Dao.SqlServer.Datas;

public partial class DivingClubEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public int? AddressId { get; set; }

    public virtual AddressEntity Address { get; set; }

    public virtual ICollection<DivingGroupEntity> DivingGroupEntities { get; set; } = new List<DivingGroupEntity>();

    public virtual ICollection<LicenceEntity> LicenceEntities { get; set; } = new List<LicenceEntity>();
}