// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DivingClubs.Dao.SqlServer.Datas;

public partial class LicenceEntity
{
    public int Id { get; set; }

    public int Rank { get; set; }

    public DateTime DateStart { get; set; }

    public DateTime? DateEnd { get; set; }

    public int? PersonId { get; set; }

    public int? ClubId { get; set; }

    public virtual DivingClubEntity Club { get; set; }

    public virtual PersonEntity Person { get; set; }

    public virtual ICollection<DivingGroupEntity> DivingGroupEntities { get; set; } = new List<DivingGroupEntity>();
}